//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS.DFe.PDF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CCeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CCeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MS.DFe.PDF.Resources.CCeResource", typeof(CCeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMBIENTE.
        /// </summary>
        internal static string AMBIENTE {
            get {
                return ResourceManager.GetString("AMBIENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOMOLOGAÇÃO - SEM VALOR FISCAL.
        /// </summary>
        internal static string AMBIENTE_HOMOLOGACAO {
            get {
                return ResourceManager.GetString("AMBIENTE_HOMOLOGACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUÇÃO.
        /// </summary>
        internal static string AMBIENTE_PRODUCAO {
            get {
                return ResourceManager.GetString("AMBIENTE_PRODUCAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itens da correção.
        /// </summary>
        internal static string CABECALHO_TABELA_CORRECAO {
            get {
                return ResourceManager.GetString("CABECALHO_TABELA_CORRECAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAVE DE ACESSO.
        /// </summary>
        internal static string CHAVE {
            get {
                return ResourceManager.GetString("CHAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ.
        /// </summary>
        internal static string CNPJ {
            get {
                return ResourceManager.GetString("CNPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Carta de Correção é disciplinada pelo § 1º-A do art. 7º do Convênio S/N, de 15 de dezembro de 1970 e pode ser utilizada para regularização de erro ocorrido na emissão de documento fiscal, desde que o erro não esteja relacionado com: 
        ///I - as variáveis que determinam o valor do imposto tais como: base de cálculo, alíquota, diferença de preço, quantidade, valor da operação ou da prestação;
        ///II - a correção de dados cadastrais que implique mudança do remetente ou do destinatário; III - a data de emissão ou d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CONDICOES_USO {
            get {
                return ResourceManager.GetString("CONDICOES_USO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATA/HORA DO EVENTO.
        /// </summary>
        internal static string DATA_HORA_EVENTO {
            get {
                return ResourceManager.GetString("DATA_HORA_EVENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATA/HORA DO REGISTRO.
        /// </summary>
        internal static string DATA_HORA_REGISTRO {
            get {
                return ResourceManager.GetString("DATA_HORA_REGISTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMPRESA.
        /// </summary>
        internal static string EMPRESA {
            get {
                return ResourceManager.GetString("EMPRESA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] logo_placeholder {
            get {
                object obj = ResourceManager.GetObject("logo_placeholder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODELO.
        /// </summary>
        internal static string MODELO {
            get {
                return ResourceManager.GetString("MODELO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NÚMERO.
        /// </summary>
        internal static string NUMERO {
            get {
                return ResourceManager.GetString("NUMERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROTOCOLO.
        /// </summary>
        internal static string PROTOCOLO {
            get {
                return ResourceManager.GetString("PROTOCOLO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SÉRIE.
        /// </summary>
        internal static string SERIE {
            get {
                return ResourceManager.GetString("SERIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não possui valor fiscal. Simples representação do evento indicado abaixo.
        /// </summary>
        internal static string SUBTITULO {
            get {
                return ResourceManager.GetString("SUBTITULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARTA DE CORREÇÃO ELETRÔNICA.
        /// </summary>
        internal static string TITULO {
            get {
                return ResourceManager.GetString("TITULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTE A AUTENTICIDADE NO SITE DA SEFAZ AUTORIZADA.
        /// </summary>
        internal static string TITULO_CONSULTE {
            get {
                return ResourceManager.GetString("TITULO_CONSULTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARTA DE CORREÇÃO ELETRÔNICA.
        /// </summary>
        internal static string TITULO_GRUPO_CARTA {
            get {
                return ResourceManager.GetString("TITULO_GRUPO_CARTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONDIÇÕES DE USO.
        /// </summary>
        internal static string TITULO_GRUPO_CONDICOES {
            get {
                return ResourceManager.GetString("TITULO_GRUPO_CONDICOES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CORREÇÃO.
        /// </summary>
        internal static string TITULO_GRUPO_CORRECAO {
            get {
                return ResourceManager.GetString("TITULO_GRUPO_CORRECAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTA FISCAL ELETRÔNICA.
        /// </summary>
        internal static string TITULO_GRUPO_NOTA {
            get {
                return ResourceManager.GetString("TITULO_GRUPO_NOTA", resourceCulture);
            }
        }
    }
}
