//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS.DFe.PDF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NFeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NFeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MS.DFe.PDF.Resources.NFeResource", typeof(NFeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALIQ..
        /// </summary>
        internal static string ALIQ {
            get {
                return ResourceManager.GetString("ALIQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B. CÁLC.
        /// </summary>
        internal static string B_CALC {
            get {
                return ResourceManager.GetString("B_CALC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAIRRO / DISTRITO.
        /// </summary>
        internal static string BAIRRO {
            get {
                return ResourceManager.GetString("BAIRRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BASE DE CÁLC. DO ICMS.
        /// </summary>
        internal static string BASE_CALCULO_ICMS {
            get {
                return ResourceManager.GetString("BASE_CALCULO_ICMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BASE DE CÁLC. ICMS S.T.
        /// </summary>
        internal static string BASE_CALCULO_ICMS_ST {
            get {
                return ResourceManager.GetString("BASE_CALCULO_ICMS_ST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÁLCULO DE IMPOSTO.
        /// </summary>
        internal static string CALCULO_IMPOSTO {
            get {
                return ResourceManager.GetString("CALCULO_IMPOSTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP.
        /// </summary>
        internal static string CEP {
            get {
                return ResourceManager.GetString("CEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CFOP.
        /// </summary>
        internal static string CFOP {
            get {
                return ResourceManager.GetString("CFOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAVE DE ACESSO.
        /// </summary>
        internal static string CHAVE_ACESSO {
            get {
                return ResourceManager.GetString("CHAVE_ACESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R$.
        /// </summary>
        internal static string CIFRAO {
            get {
                return ResourceManager.GetString("CIFRAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ.
        /// </summary>
        internal static string CNPJ {
            get {
                return ResourceManager.GetString("CNPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ / CPF.
        /// </summary>
        internal static string CNPJ_CPF {
            get {
                return ResourceManager.GetString("CNPJ_CPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÓDIGO ANTT.
        /// </summary>
        internal static string CODIGO_ANTT {
            get {
                return ResourceManager.GetString("CODIGO_ANTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÓDIGO PRODUTO.
        /// </summary>
        internal static string CODIGO_PRODUTO {
            get {
                return ResourceManager.GetString("CODIGO_PRODUTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta de autenticidade no portal nacional da NF-e.
        /// </summary>
        internal static string CONSULTA_AUTENTICIDADE {
            get {
                return ResourceManager.GetString("CONSULTA_AUTENTICIDADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O/CST.
        /// </summary>
        internal static string CST {
            get {
                return ResourceManager.GetString("CST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DADOS ADICIONAIS.
        /// </summary>
        internal static string DADOS_ADICIONAIS {
            get {
                return ResourceManager.GetString("DADOS_ADICIONAIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DADOS DOS PRODUTOS / SERVICOS.
        /// </summary>
        internal static string DADOS_PRODUTOS_SERVICOS {
            get {
                return ResourceManager.GetString("DADOS_PRODUTOS_SERVICOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DANFE.
        /// </summary>
        internal static string DANFE {
            get {
                return ResourceManager.GetString("DANFE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATA DE EMISSÃO.
        /// </summary>
        internal static string DATA_EMISSAO {
            get {
                return ResourceManager.GetString("DATA_EMISSAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATA ENTRADA / SAÍDA.
        /// </summary>
        internal static string DATA_ENTRADA_SAIDA {
            get {
                return ResourceManager.GetString("DATA_ENTRADA_SAIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATA DE RECEBIMENTO.
        /// </summary>
        internal static string DATA_RECEBIMENTO {
            get {
                return ResourceManager.GetString("DATA_RECEBIMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESCONTO.
        /// </summary>
        internal static string DESCONTO {
            get {
                return ResourceManager.GetString("DESCONTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESCRIÇÃO DO PRODUTO / SERVIÇO.
        /// </summary>
        internal static string DESCRIÇÃO_PRODUTO_SERVIÇO {
            get {
                return ResourceManager.GetString("DESCRIÇÃO_PRODUTO_SERVIÇO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinatártio:.
        /// </summary>
        internal static string DESTINATARIO {
            get {
                return ResourceManager.GetString("DESTINATARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESTINATARIO / REMETENTE.
        /// </summary>
        internal static string DESTINATARIO_REMETENTE {
            get {
                return ResourceManager.GetString("DESTINATARIO_REMETENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento Auxiliar da \r\nNota Fiscal Eletrônica.
        /// </summary>
        internal static string DOCUMENTO_AUXILIAR {
            get {
                return ResourceManager.GetString("DOCUMENTO_AUXILIAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emissão:.
        /// </summary>
        internal static string EMISSAO {
            get {
                return ResourceManager.GetString("EMISSAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENDEREÇO.
        /// </summary>
        internal static string ENDERECO {
            get {
                return ResourceManager.GetString("ENDERECO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 - ENTRADA.
        /// </summary>
        internal static string ENTRADA {
            get {
                return ResourceManager.GetString("ENTRADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESPÉCIE.
        /// </summary>
        internal static string ESPECIE {
            get {
                return ResourceManager.GetString("ESPECIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FATURA / DUPLICATA.
        /// </summary>
        internal static string FATURA_DUPLICATA {
            get {
                return ResourceManager.GetString("FATURA_DUPLICATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fone.
        /// </summary>
        internal static string FONE {
            get {
                return ResourceManager.GetString("FONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FONE / FAX.
        /// </summary>
        internal static string FONE_FAX {
            get {
                return ResourceManager.GetString("FONE_FAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRETE.
        /// </summary>
        internal static string FRETE {
            get {
                return ResourceManager.GetString("FRETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HORA_ENTRADA_SAÍDA.
        /// </summary>
        internal static string HORA_ENTRADA_SAÍDA {
            get {
                return ResourceManager.GetString("HORA_ENTRADA_SAÍDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICMS.
        /// </summary>
        internal static string ICMS {
            get {
                return ResourceManager.GetString("ICMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDENTIFICAÇÃO E ASSINATURA DO RECEBEDOR.
        /// </summary>
        internal static string IDENTIFICACAO_ASSINATURA_RECEBEDOR {
            get {
                return ResourceManager.GetString("IDENTIFICACAO_ASSINATURA_RECEBEDOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDENTIFICAÇÃO DO EMITENTE.
        /// </summary>
        internal static string IDENTIFICACAO_EMITENTE {
            get {
                return ResourceManager.GetString("IDENTIFICACAO_EMITENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inf. Contribuente:.
        /// </summary>
        internal static string INF_CONTRIBUENTE {
            get {
                return ResourceManager.GetString("INF_CONTRIBUENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inf. Fisco:.
        /// </summary>
        internal static string INF_FISCO {
            get {
                return ResourceManager.GetString("INF_FISCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFORMAÇÕES COMPLEMENTARES.
        /// </summary>
        internal static string INFORMAÇÕES_COMPLEMENTARES {
            get {
                return ResourceManager.GetString("INFORMAÇÕES_COMPLEMENTARES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSCRIÇÃO ESTADUAL.
        /// </summary>
        internal static string INSCRICAO_ESTADUAL {
            get {
                return ResourceManager.GetString("INSCRICAO_ESTADUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSCRIÇÃO ESTADUAL DO SUBST. TRIBUTÁRIO.
        /// </summary>
        internal static string INSCRICAO_ESTADUAL_SUBST_TRIBUTÁRIO {
            get {
                return ResourceManager.GetString("INSCRICAO_ESTADUAL_SUBST_TRIBUTÁRIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPI.
        /// </summary>
        internal static string IPI {
            get {
                return ResourceManager.GetString("IPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARCA.
        /// </summary>
        internal static string MARCA {
            get {
                return ResourceManager.GetString("MARCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento impresso por MicroSales - www.microsales.com.br.
        /// </summary>
        internal static string MICROSALES_INFO {
            get {
                return ResourceManager.GetString("MICROSALES_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipio.
        /// </summary>
        internal static string MUNICIPIO {
            get {
                return ResourceManager.GetString("MUNICIPIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NATUREZA DA OPERAÇÃO.
        /// </summary>
        internal static string NATUREZA_OPERACAO {
            get {
                return ResourceManager.GetString("NATUREZA_OPERACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NCM/SH.
        /// </summary>
        internal static string NCM_SH {
            get {
                return ResourceManager.GetString("NCM_SH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NF-e.
        /// </summary>
        internal static string NFE {
            get {
                return ResourceManager.GetString("NFE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NULL {
            get {
                return ResourceManager.GetString("NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUMERAÇÃO.
        /// </summary>
        internal static string NUMERACAO {
            get {
                return ResourceManager.GetString("NUMERACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº.
        /// </summary>
        internal static string NUMERO {
            get {
                return ResourceManager.GetString("NUMERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número:.
        /// </summary>
        internal static string NUMERO_VALOR {
            get {
                return ResourceManager.GetString("NUMERO_VALOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O/CSOSN.
        /// </summary>
        internal static string O_CSOSN {
            get {
                return ResourceManager.GetString("O_CSOSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUTRAS DESPESAS.
        /// </summary>
        internal static string OUTRAS_DESPESAS {
            get {
                return ResourceManager.GetString("OUTRAS_DESPESAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PESO BRUTO.
        /// </summary>
        internal static string PESO_BRUTO {
            get {
                return ResourceManager.GetString("PESO_BRUTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PESO LÍQUIDO.
        /// </summary>
        internal static string PESO_LIQUIDO {
            get {
                return ResourceManager.GetString("PESO_LIQUIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLACA DO VEÍCULO.
        /// </summary>
        internal static string PLACA_VEICULO {
            get {
                return ResourceManager.GetString("PLACA_VEICULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to os produtos e/ou serviços constantes na Nota Fiscal Eletrônica indicada abaixo..
        /// </summary>
        internal static string PRODUTOS_SERVICOS {
            get {
                return ResourceManager.GetString("PRODUTOS_SERVICOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROTOCOLO DE AUTORIZAÇÃO.
        /// </summary>
        internal static string PROTOCOLO_AUTORIZACAO {
            get {
                return ResourceManager.GetString("PROTOCOLO_AUTORIZACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUANTI..
        /// </summary>
        internal static string QUANTI {
            get {
                return ResourceManager.GetString("QUANTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUANTIDADE.
        /// </summary>
        internal static string QUANTIDADE {
            get {
                return ResourceManager.GetString("QUANTIDADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAZÃO SOCIAL.
        /// </summary>
        internal static string RAZAO_SOCIAL {
            get {
                return ResourceManager.GetString("RAZAO_SOCIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recebemos de.
        /// </summary>
        internal static string RECEBEMOS {
            get {
                return ResourceManager.GetString("RECEBEMOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESERVADO AO FISCO.
        /// </summary>
        internal static string RESERVADO_FISCO {
            get {
                return ResourceManager.GetString("RESERVADO_FISCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - SAÍDA.
        /// </summary>
        internal static string SAIDA {
            get {
                return ResourceManager.GetString("SAIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Série:.
        /// </summary>
        internal static string SERIE {
            get {
                return ResourceManager.GetString("SERIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL.
        /// </summary>
        internal static string TOTAL {
            get {
                return ResourceManager.GetString("TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANSPORTADOR / VOLUMES TRANSPORTADOS.
        /// </summary>
        internal static string TRANSPORTADOR {
            get {
                return ResourceManager.GetString("TRANSPORTADOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UF.
        /// </summary>
        internal static string UF {
            get {
                return ResourceManager.GetString("UF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UN.
        /// </summary>
        internal static string UN {
            get {
                return ResourceManager.GetString("UN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNIT.
        /// </summary>
        internal static string UNIT {
            get {
                return ResourceManager.GetString("UNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.nfe.fazenda.gov.br/portal ou no site da Sefaz Autorizadora.
        /// </summary>
        internal static string URL_NFE {
            get {
                return ResourceManager.GetString("URL_NFE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V. ICMS UF DEST.
        /// </summary>
        internal static string V_ICMS_UF_DEST {
            get {
                return ResourceManager.GetString("V_ICMS_UF_DEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V. ICMS UF REMET.
        /// </summary>
        internal static string V_ICMS_UF_REMET {
            get {
                return ResourceManager.GetString("V_ICMS_UF_REMET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V. IMP. IMPORTAÇÃO.
        /// </summary>
        internal static string V_IMP_IMPORTAÇÃO {
            get {
                return ResourceManager.GetString("V_IMP_IMPORTAÇÃO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V. TOT. TRIB..
        /// </summary>
        internal static string V_TOT_TRIB {
            get {
                return ResourceManager.GetString("V_TOT_TRIB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V. TOTAL PRODUTOS.
        /// </summary>
        internal static string V_TOTAL_PRODUTOS {
            get {
                return ResourceManager.GetString("V_TOTAL_PRODUTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALOR.
        /// </summary>
        internal static string VALOR {
            get {
                return ResourceManager.GetString("VALOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Aproximado dos Tributos:.
        /// </summary>
        internal static string VALOR_APROXIMADO_TRIBUTOS {
            get {
                return ResourceManager.GetString("VALOR_APROXIMADO_TRIBUTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALOR DO COFINS.
        /// </summary>
        internal static string VALOR_COFINS {
            get {
                return ResourceManager.GetString("VALOR_COFINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALOR DO FCP.
        /// </summary>
        internal static string VALOR_FCP {
            get {
                return ResourceManager.GetString("VALOR_FCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALOR DO FRETE.
        /// </summary>
        internal static string VALOR_FRETE {
            get {
                return ResourceManager.GetString("VALOR_FRETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALOR DO ICMS.
        /// </summary>
        internal static string VALOR_ICMS {
            get {
                return ResourceManager.GetString("VALOR_ICMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALOR DO ICMS SUBST.
        /// </summary>
        internal static string VALOR_ICMS_SUBST {
            get {
                return ResourceManager.GetString("VALOR_ICMS_SUBST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor:.
        /// </summary>
        internal static string VALOR_INF {
            get {
                return ResourceManager.GetString("VALOR_INF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALOR IPI.
        /// </summary>
        internal static string VALOR_IPI {
            get {
                return ResourceManager.GetString("VALOR_IPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALOR DO PIS.
        /// </summary>
        internal static string VALOR_PIS {
            get {
                return ResourceManager.GetString("VALOR_PIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALOR DO SEGURO.
        /// </summary>
        internal static string VALOR_SEGURO {
            get {
                return ResourceManager.GetString("VALOR_SEGURO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Total:.
        /// </summary>
        internal static string VALOR_TOTAL {
            get {
                return ResourceManager.GetString("VALOR_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALOR TOTAL DA NOTA.
        /// </summary>
        internal static string VALOR_TOTAL_NOTA {
            get {
                return ResourceManager.GetString("VALOR_TOTAL_NOTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALOR DO ICMS SUBST..
        /// </summary>
        internal static string VALOS_ICMS_SUBST {
            get {
                return ResourceManager.GetString("VALOS_ICMS_SUBST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vencimento:.
        /// </summary>
        internal static string VENCIMENTO {
            get {
                return ResourceManager.GetString("VENCIMENTO", resourceCulture);
            }
        }
    }
}
