//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS.DFe.PDF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextoResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MS.DFe.PDF.Resources.TextoResource", typeof(TextoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R$.
        /// </summary>
        internal static string CIFRAO {
            get {
                return ResourceManager.GetString("CIFRAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ.
        /// </summary>
        internal static string CNPJ {
            get {
                return ResourceManager.GetString("CNPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        internal static string CODIGO {
            get {
                return ResourceManager.GetString("CODIGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulte pela Chave de Acesso em.
        /// </summary>
        internal static string CONSULTE_CHAVE {
            get {
                return ResourceManager.GetString("CONSULTE_CHAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSUMIDOR.
        /// </summary>
        internal static string CONSUMIDOR {
            get {
                return ResourceManager.GetString("CONSUMIDOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSUMIDOR NÃO IDENTIFICADO.
        /// </summary>
        internal static string CONSUMIDOR_NAO_IDENTIFICADO {
            get {
                return ResourceManager.GetString("CONSUMIDOR_NAO_IDENTIFICADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        internal static string CPF {
            get {
                return ResourceManager.GetString("CPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DANFE NFC-e.
        /// </summary>
        internal static string DANFE {
            get {
                return ResourceManager.GetString("DANFE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de autorização.
        /// </summary>
        internal static string DATA {
            get {
                return ResourceManager.GetString("DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desconto.
        /// </summary>
        internal static string DESCONTO {
            get {
                return ResourceManager.GetString("DESCONTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        internal static string DESCRICAO {
            get {
                return ResourceManager.GetString("DESCRICAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento Auxiliar da Nota Fiscal de Consumidor Eletronica.
        /// </summary>
        internal static string DOC_AUX {
            get {
                return ResourceManager.GetString("DOC_AUX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORMA PAGAMENTO.
        /// </summary>
        internal static string FORMA_PAGAMENTO {
            get {
                return ResourceManager.GetString("FORMA_PAGAMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy HH:mm:ss.
        /// </summary>
        internal static string FORMATO {
            get {
                return ResourceManager.GetString("FORMATO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frete.
        /// </summary>
        internal static string FRETE {
            get {
                return ResourceManager.GetString("FRETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFC-e nº.
        /// </summary>
        internal static string NFCE_NR {
            get {
                return ResourceManager.GetString("NFCE_NR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outras despesas.
        /// </summary>
        internal static string OUTROS {
            get {
                return ResourceManager.GetString("OUTROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor a Pagar.
        /// </summary>
        internal static string PAGAR {
            get {
                return ResourceManager.GetString("PAGAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALOR PAGO.
        /// </summary>
        internal static string PAGO {
            get {
                return ResourceManager.GetString("PAGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocolo de autorização.
        /// </summary>
        internal static string PROTOCOLO {
            get {
                return ResourceManager.GetString("PROTOCOLO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qtde UN.
        /// </summary>
        internal static string QTDE {
            get {
                return ResourceManager.GetString("QTDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qtde total de itens.
        /// </summary>
        internal static string QTDE_TOTAL_ITENS {
            get {
                return ResourceManager.GetString("QTDE_TOTAL_ITENS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguro.
        /// </summary>
        internal static string SEGURO {
            get {
                return ResourceManager.GetString("SEGURO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Série.
        /// </summary>
        internal static string SERIE {
            get {
                return ResourceManager.GetString("SERIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Total.
        /// </summary>
        internal static string TOTAL {
            get {
                return ResourceManager.GetString("TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tributos Totais Incidentes (Lei Federal 12.741/2012).
        /// </summary>
        internal static string TRIBUTOS {
            get {
                return ResourceManager.GetString("TRIBUTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troco.
        /// </summary>
        internal static string TROCO {
            get {
                return ResourceManager.GetString("TROCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vl Unit.
        /// </summary>
        internal static string UNITARIO {
            get {
                return ResourceManager.GetString("UNITARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Via Consumidor.
        /// </summary>
        internal static string VIA_CONSUMIDOR {
            get {
                return ResourceManager.GetString("VIA_CONSUMIDOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vl Total.
        /// </summary>
        internal static string VL_TOTAL {
            get {
                return ResourceManager.GetString("VL_TOTAL", resourceCulture);
            }
        }
    }
}
